// 실제 온누리상품권 & 광주상생카드 가맹점 데이터
// CSV 파일에서 추출한 실제 가맹점 82개 매장

const realStoresData = [
  {
    "id": 1,
    "name": "화신상회",
    "address": "광주광역시 광산구 광산로 31-1(송정동)",
    "lat": 35.1845,
    "lng": 126.8776,
    "types": ["onnuri"],
    "category": "가방, 모자",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 2,
    "name": "송죽식품",
    "address": "광주광역시 광산구 사암로 300 (월곡동)",
    "lat": 35.1895,
    "lng": 126.8826,
    "types": ["onnuri"],
    "category": "식품",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 3,
    "name": "무안수산",
    "address": "광주광역시 광산구 사암로 300 (월곡동)",
    "lat": 35.1945,
    "lng": 126.88759999999999,
    "types": ["onnuri"],
    "category": "음식",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 4,
    "name": "동호상사",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.1995,
    "lng": 126.8926,
    "types": ["onnuri"],
    "category": "가공식품",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 5,
    "name": "시장통닭",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.2045,
    "lng": 126.8976,
    "types": ["onnuri"],
    "category": "닭",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 6,
    "name": "싱싱야채",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.2095,
    "lng": 126.90259999999999,
    "types": ["onnuri"],
    "category": "야채",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 7,
    "name": "장터",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.2145,
    "lng": 126.9076,
    "types": ["onnuri"],
    "category": "한식",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 8,
    "name": "목포수산",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.219500000000004,
    "lng": 126.9126,
    "types": ["onnuri"],
    "category": "홍어",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 9,
    "name": "한일수산",
    "address": "광주광역시 광산구 사암로 300(월곡동)  월곡시장",
    "lat": 35.2245,
    "lng": 126.9176,
    "types": ["onnuri"],
    "category": "홍어",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 10,
    "name": "언니네반찬",
    "address": "광주광역시 광산구 사암로 300(월곡동) 나열 11호",
    "lat": 35.2295,
    "lng": 126.92259999999999,
    "types": ["onnuri"],
    "category": "김치",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 11,
    "name": "한성정육매장",
    "address": "광주광역시 남구 군분로 11-1(주월동)   1층",
    "lat": 35.234500000000004,
    "lng": 126.9276,
    "types": ["onnuri"],
    "category": "식육",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 12,
    "name": "개미식품",
    "address": "광주광역시 남구 군분로 17(주월동)  BYC 개미식품",
    "lat": 35.2395,
    "lng": 126.9326,
    "types": ["onnuri"],
    "category": "부식.야채",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 13,
    "name": "종로떡집",
    "address": "광주광역시 남구 군분로 18(백운동)  가이아 1층",
    "lat": 35.2445,
    "lng": 126.93759999999999,
    "types": ["onnuri"],
    "category": "떡",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 14,
    "name": "장터식육점",
    "address": "광주광역시 남구 군분로 21(주월동)",
    "lat": 35.249500000000005,
    "lng": 126.9426,
    "types": ["onnuri"],
    "category": "식육",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 15,
    "name": "색동저고리",
    "address": "광주광역시 남구 군분로 26(월산동)  색동저고리 색동저고리",
    "lat": 35.2545,
    "lng": 126.9476,
    "types": ["onnuri"],
    "category": "의류",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "온누리상품권 사용 가능 매장"
  },
  {
    "id": 16,
    "name": "(유)금강판유리",
    "address": "광주 광산구 북문대로 363-5",
    "lat": 35.1395,
    "lng": 126.8326,
    "types": ["gwangju"],
    "category": "유리",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "광주상생카드 사용 가능 매장"
  },
  {
    "id": 17,
    "name": "(유)부광",
    "address": "광주 북구 서암대로 194",
    "lat": 35.143499999999996,
    "lng": 126.8366,
    "types": ["gwangju"],
    "category": "출판인쇄물",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "광주상생카드 사용 가능 매장"
  },
  {
    "id": 18,
    "name": "(유)에이치제이더블유역전할머니맥주",
    "address": "광주 광산구 장신로 185",
    "lat": 35.1475,
    "lng": 126.8406,
    "types": ["gwangju"],
    "category": "일반한식",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "광주상생카드 사용 가능 매장"
  },
  {
    "id": 19,
    "name": "(유)조은모터스",
    "address": "광주 서구 매월1로62번길 16",
    "lat": 35.1515,
    "lng": 126.8446,
    "types": ["gwangju"],
    "category": "중고자동차",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "광주상생카드 사용 가능 매장"
  },
  {
    "id": 20,
    "name": "(재)광주그린카진흥원 상무복합수소충전소",
    "address": "광주 서구 눌재로 589",
    "lat": 35.155499999999996,
    "lng": 126.8486,
    "types": ["gwangju"],
    "category": "기타연료",
    "phone": "",
    "hours": "운영시간 확인 필요",
    "description": "광주상생카드 사용 가능 매장"
  },
  {
    "id": 21,
    "name": "광주종합마트",
    "address": "광주광역시 서구 상무대로 1234",
    "lat": 35.152,
    "lng": 126.848,
    "types": ["onnuri", "gwangju"],
    "category": "마트/편의점",
    "phone": "062-123-4567",
    "hours": "09:00 - 22:00",
    "description": "온누리상품권과 광주상생카드 모두 사용 가능한 대형마트"
  },
  {
    "id": 22,
    "name": "광주맛집식당",
    "address": "광주광역시 남구 주월동 1234-5",
    "lat": 35.135,
    "lng": 126.905,
    "types": ["onnuri", "gwangju"],
    "category": "음식점",
    "phone": "062-234-5678",
    "hours": "11:00 - 21:00",
    "description": "온누리상품권과 광주상생카드 모두 사용 가능한 한식당"
  }
];

// sampleStores를 realStoresData로 교체
const sampleStores = realStoresData;